### ISSUE TITLE
flexdashboard issue

### ISSUE THREAD

**Issue by bharatbrijwasi** [pbatey/flexdashboard-example#1]
I create an RMD file using flexdashboard template with an index.Rmd and _site.yml and want to host on the Github page. but, it gives an error for hosting. please guide me.

**Comment by pbatey** [comment]
What's the error?

**Comment by bharatbrijwasi** [comment]
404
There isn't a GitHub Pages site here.

If you're trying to publish one, read the full documentation to learn how to set up GitHub Pages for your repository, organization, or user account.

GitHub Status — @githubstatus

**Comment by bharatbrijwasi** [comment]
can you send me full documentation related to "how to host flexdashboard on Github page step by step"
Note: if possible please send me on my Email.
email-bharatbrijwasi777@gmail.com

**Comment by pbatey** [comment]
Looks like you were able to set it up to me -- https://bharatbrijwasi.github.io/coronanews/

What URL were you expecting it to be located at?

**Comment by bharatbrijwasi** [comment]
i just deploy my own page on Github by itself without fork your repo but i don't do that

**Comment by pbatey** [comment]
I'm sorry, but I'm having a hard time understanding the problem you are having. I don't have any documentation other than the steps that I outlined in the readme on this repo. BTW: I'm on a Mac and I use brew to install most command-line software. I'm not as familiar with how to do it on other operating systems.

I'd like to help you, but you aren't being very clear about what you are trying to accomplish or what commands you are struggling with.

**Comment by bharatbrijwasi** [comment]
step that i follow.
1. create new repo on github with README and gitignore(R)
2.after open Rstudio, file>>new Project >>git version >> paste repo url>> create project
3. file>> rmarkdown>> from template >>select Flex dashboard >> ok >> save file by index.Rmd without any change.
4. create new text file >> write into file [name: "my-website"   output_dir: docs] >> and save _site.yml

5. open console >> run - rmarkdown::render_site()
6. afte this by using Rstudio terminal--
    git add .
    git commit -m "first commit"
    git push -u  origin branchName

7. after finishing this open github 
   goto setting >> build page

**Comment by pbatey** [comment]
Did you set Source to master branch /docs folder in the GitHub Pages section of the repository settings?

**Comment by bharatbrijwasi** [comment]
yes

**Comment by bharatbrijwasi** [comment]
is there any problem in the above step that i follow

**Comment by pbatey** [comment]
Can you point me to the repo so I can take a look? Is it the cars one? https://bharatbrijwasi.github.io/cars/?

**Comment by bharatbrijwasi** [comment]
i deleted that repo i make new repo and host that please wait for a while

**Comment by bharatbrijwasi** [comment]
sir please check this..
https://github.com/bharatbrijwasi/Test

**Comment by pbatey** [comment]
Looks like it worked to me: https://bharatbrijwasi.github.io/Test/

Can you see that URL?

**Comment by bharatbrijwasi** [comment]
> Looks like it worked to me: https://bharatbrijwasi.github.io/Test/
> 
> Can you see that URL?

yes URL is same but it gives 404 error

**Comment by bharatbrijwasi** [comment]
sir now it's working  https://bharatbrijwasi.github.io/Test/ i don't know how

**Comment by bharatbrijwasi** [comment]
thanks alot sir for give me your valuable time

**Comment by pbatey** [comment]
That's great news! I'm glad it's working for you.
